name: Measure Build Time

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  measure-time:
    runs-on: ubuntu-latest

    steps:
      - name: Record start time
        id: start
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Simulate installation steps
        run: |
          echo "Installing dependencies..."
          sleep 90  # Simulate ~1.5 minutes
          echo "Done!"

      - name: Record end time and calculate duration
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          MINUTES=$((DURATION / 60))
          SECONDS=$((DURATION % 60))
          echo "✅ Build completed in ${MINUTES} min ${SECONDS} sec"
        env:
          START_TIME: ${{ env.START_TIME }}
